name: Manual workflow

on:
  workflow_dispatch:   # allows you to run manually from the GitHub Actions UI

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BOOKING_GOALS: '{"4":{"time":"0930","name":"Open Box"}}'
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: make docker/build

      - name: Run fitbot
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals "$BOOKING_GOALS" -e box-name=ensocrossfit -e box-id=8298 -e days-in-advance=1 -e proxy=${{ secrets.PROXY }} fitbot
